steps:
# 1. Construir (Usamos el constructor oficial de Docker)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: 
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/nextum-labs/nextumlabs-repo/nextumlabs-app:$COMMIT_SHA'
    - '-t'
    - 'us-central1-docker.pkg.dev/nextum-labs/nextumlabs-repo/nextumlabs-app:latest'
    - '.'

# 2. Subir ambas etiquetas (Usamos el constructor oficial de Docker)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push SHA'
  args: ['push', 'us-central1-docker.pkg.dev/nextum-labs/nextumlabs-repo/nextumlabs-app:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Latest'
  args: ['push', 'us-central1-docker.pkg.dev/nextum-labs/nextumlabs-repo/nextumlabs-app:latest']

# 3. Desplegar (Usamos el constructor oficial de GKE)
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Deploy'
  args:
  - run
  - --filename=k8s/nextum-app.yaml
  - --location=us-central1
  - --cluster=nextumlabs-cluster

options:
  logging: CLOUD_LOGGING_ONLY
